"""原版 QQ宠物 打工/学习数据（提取自 pet_1.2.4_asar shop.js work/study 段）。"""

WORK = {
 "bz": {"id": "bz", "name": "搬砖", "charm": 0, "intel": 0, "strong": 1, "clean": 200, "starve": 300, "mood": 90, "yb": 10, "use_time": 30, "need": 0, "education": {}},
 "nwg": {"id": "nwg", "name": "泥瓦工", "charm": 0, "intel": 1, "strong": 1, "clean": 300, "starve": 200, "mood": 80, "yb": 10, "use_time": 30, "need": 3, "education": {"labouring": 9}},
 "hj": {"id": "hj", "name": "花匠", "charm": 10, "intel": 0, "strong": 0, "clean": 100, "starve": 300, "mood": 80, "yb": 13, "use_time": 30, "need": 6, "education": {"manner": 9}},
 "yd": {"id": "yd", "name": "园丁", "charm": 0, "intel": 10, "strong": 0, "clean": 300, "starve": 400, "mood": 80, "yb": 14, "use_time": 30, "need": 9, "education": {"chinese": 9, "art": 9}},
 "mj": {"id": "mj", "name": "木匠", "charm": 0, "intel": 10, "strong": 0, "clean": 300, "starve": 400, "mood": 80, "yb": 13, "use_time": 30, "need": 6, "education": {"labouring": 9}},
 "jzs": {"id": "jzs", "name": "建筑师", "charm": 0, "intel": 10, "strong": 0, "clean": 300, "starve": 400, "mood": 80, "yb": 20, "use_time": 30, "need": 24, "education": {"art": 40, "mathematics": 40}},
 "ba": {"id": "ba", "name": "保安", "charm": 0, "intel": 0, "strong": 10, "clean": 300, "starve": 300, "mood": 80, "yb": 14, "use_time": 30, "need": 9, "education": {"politics": 9, "wushu": 9}},
 "yy": {"id": "yy", "name": "演员", "charm": 20, "intel": 0, "strong": 0, "clean": 100, "starve": 500, "mood": 80, "yb": 14, "use_time": 30, "need": 9, "education": {"manner": 9, "labouring": 9}},
 "jl": {"id": "jl", "name": "教练", "charm": 40, "intel": 50, "strong": 0, "clean": 500, "starve": 500, "mood": 20, "yb": 16, "use_time": 30, "need": 12, "education": {"pe": 40}},
 "ls": {"id": "ls", "name": "律师", "charm": 0, "intel": 30, "strong": 0, "clean": 100, "starve": 300, "mood": 80, "yb": 16, "use_time": 30, "need": 12, "education": {"politics": 20}},
 "gs": {"id": "gs", "name": "歌手", "charm": 40, "intel": 0, "strong": 0, "clean": 200, "starve": 400, "mood": 80, "yb": 16, "use_time": 30, "need": 12, "education": {"music": 20}},
 "mhj": {"id": "mhj", "name": "漫画家", "charm": 0, "intel": 40, "strong": 0, "clean": 100, "starve": 100, "mood": 20, "yb": 80, "use_time": 30, "need": 15, "education": {"art": 20, "labouring": 20}},
 "jc": {"id": "jc", "name": "警察", "charm": 50, "intel": 50, "strong": 50, "clean": 500, "starve": 500, "mood": 20, "yb": 17, "use_time": 30, "need": 15, "education": {"politics": 20, "wushu": 20}},
 "cqz": {"id": "cqz", "name": "词曲者", "charm": 50, "intel": 20, "strong": 0, "clean": 100, "starve": 100, "mood": 20, "yb": 17, "use_time": 30, "need": 15, "education": {"chinese": 20, "music": 20}},
 "bj": {"id": "bj", "name": "编辑", "charm": 10, "intel": 50, "strong": 0, "clean": 100, "starve": 300, "mood": 20, "yb": 18, "use_time": 30, "need": 18, "education": {"chinese": 40}},
 "sys": {"id": "sys", "name": "摄影师", "charm": 100, "intel": 100, "strong": 100, "clean": 500, "starve": 500, "mood": 20, "yb": 18, "use_time": 30, "need": 18, "education": {"art": 40}},
 "zdx": {"id": "zdx", "name": "科研人员", "charm": 200, "intel": 200, "strong": 200, "clean": 500, "starve": 500, "mood": 20, "yb": 1024, "use_time": 80, "need": 19, "education": {"chinese": 40, "mathematics": 40, "art": 40, "pe": 40}},
 "spg": {"id": "spg", "name": "公务员", "charm": 2048, "intel": 2048, "strong": 2048, "clean": 300, "starve": 300, "mood": 20, "yb": 2048, "use_time": 120, "need": 19, "education": {"chinese": 40, "mathematics": 40, "politics": 40, "music": 40, "art": 40, "manner": 40, "pe": 40, "labouring": 40, "wushu": 40}},
}

STUDY = {
 "xx-chinese": {"id": "xx-chinese", "object": "语文", "subject": "chinese", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学语文", "charm": 5, "intel": 15, "strong": 0, "starve": 90, "clean": 0},
 "xx-mathematics": {"id": "xx-mathematics", "object": "数学", "subject": "mathematics", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学数学", "charm": 0, "intel": 20, "strong": 0, "starve": 135, "clean": 0},
 "xx-politics": {"id": "xx-politics", "object": "政治", "subject": "politics", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学政治", "charm": 0, "intel": 25, "strong": 0, "starve": 180, "clean": 0},
 "xx-music": {"id": "xx-music", "object": "音乐", "subject": "music", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学音乐", "charm": 15, "intel": 0, "strong": 0, "starve": 45, "clean": 0},
 "xx-art": {"id": "xx-art", "object": "艺术", "subject": "art", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学艺术", "charm": 20, "intel": 20, "strong": 0, "starve": 135, "clean": 90},
 "xx-manner": {"id": "xx-manner", "object": "礼仪", "subject": "manner", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学礼仪", "charm": 20, "intel": 0, "strong": 0, "starve": 90, "clean": 45},
 "xx-pe": {"id": "xx-pe", "object": "体育", "subject": "pe", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学体育", "charm": 0, "intel": 0, "strong": 15, "starve": 90, "clean": 90},
 "xx-labouring": {"id": "xx-labouring", "object": "劳技", "subject": "labouring", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学劳技", "charm": 0, "intel": 0, "strong": 10, "starve": 90, "clean": 45},
 "xx-wushu": {"id": "xx-wushu", "object": "武术", "subject": "wushu", "school": "小学", "class_num_up": 0, "class_num": 9, "class_time": 45, "tolk_name": "小学武术", "charm": 0, "intel": 0, "strong": 25, "starve": 180, "clean": 180},
 "zx-chinese": {"id": "zx-chinese", "object": "语文", "subject": "chinese", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学语文", "charm": 15, "intel": 25, "strong": 0, "starve": 90, "clean": 0},
 "zx-mathematics": {"id": "zx-mathematics", "object": "数学", "subject": "mathematics", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学数学", "charm": 10, "intel": 30, "strong": 0, "starve": 135, "clean": 0},
 "zx-politics": {"id": "zx-politics", "object": "政治", "subject": "politics", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学政治", "charm": 0, "intel": 35, "strong": 0, "starve": 180, "clean": 0},
 "zx-music": {"id": "zx-music", "object": "音乐", "subject": "music", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学音乐", "charm": 25, "intel": 0, "strong": 0, "starve": 45, "clean": 0},
 "zx-art": {"id": "zx-art", "object": "艺术", "subject": "art", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学艺术", "charm": 30, "intel": 30, "strong": 0, "starve": 135, "clean": 90},
 "zx-manner": {"id": "zx-manner", "object": "礼仪", "subject": "manner", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学礼仪", "charm": 30, "intel": 0, "strong": 0, "starve": 90, "clean": 45},
 "zx-pe": {"id": "zx-pe", "object": "体育", "subject": "pe", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学体育", "charm": 5, "intel": 0, "strong": 25, "starve": 90, "clean": 90},
 "zx-labouring": {"id": "zx-labouring", "object": "劳技", "subject": "labouring", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学劳技", "charm": 0, "intel": 0, "strong": 20, "starve": 90, "clean": 45},
 "zx-wushu": {"id": "zx-wushu", "object": "武术", "subject": "wushu", "school": "中学", "class_num_up": 9, "class_num": 20, "class_time": 45, "tolk_name": "中学武术", "charm": 0, "intel": 0, "strong": 35, "starve": 180, "clean": 180},
 "dx-chinese": {"id": "dx-chinese", "object": "语文", "subject": "chinese", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学语文", "charm": 35, "intel": 45, "strong": 0, "starve": 110, "clean": 0},
 "dx-mathematics": {"id": "dx-mathematics", "object": "数学", "subject": "mathematics", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学数学", "charm": 30, "intel": 50, "strong": 0, "starve": 165, "clean": 0},
 "dx-politics": {"id": "dx-politics", "object": "政治", "subject": "politics", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学政治", "charm": 0, "intel": 55, "strong": 0, "starve": 220, "clean": 0},
 "dx-music": {"id": "dx-music", "object": "音乐", "subject": "music", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学音乐", "charm": 45, "intel": 0, "strong": 0, "starve": 55, "clean": 0},
 "dx-art": {"id": "dx-art", "object": "艺术", "subject": "art", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学艺术", "charm": 50, "intel": 50, "strong": 0, "starve": 165, "clean": 110},
 "dx-manner": {"id": "dx-manner", "object": "礼仪", "subject": "manner", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学礼仪", "charm": 50, "intel": 0, "strong": 0, "starve": 110, "clean": 55},
 "dx-pe": {"id": "dx-pe", "object": "体育", "subject": "pe", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学体育", "charm": 25, "intel": 0, "strong": 45, "starve": 110, "clean": 110},
 "dx-labouring": {"id": "dx-labouring", "object": "劳技", "subject": "labouring", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学劳技", "charm": 20, "intel": 0, "strong": 40, "starve": 110, "clean": 55},
 "dx-wushu": {"id": "dx-wushu", "object": "武术", "subject": "wushu", "school": "大学", "class_num_up": 29, "class_num": 40, "class_time": 55, "tolk_name": "大学武术", "charm": 0, "intel": 0, "strong": 55, "starve": 220, "clean": 220},
 "yjs-chinese": {"id": "yjs-chinese", "object": "语文", "subject": "chinese", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生语文", "charm": 75, "intel": 85, "strong": 0, "starve": 110, "clean": 0},
 "yjs-mathematics": {"id": "yjs-mathematics", "object": "数学", "subject": "mathematics", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生数学", "charm": 70, "intel": 90, "strong": 0, "starve": 165, "clean": 0},
 "yjs-politics": {"id": "yjs-politics", "object": "政治", "subject": "politics", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生政治", "charm": 0, "intel": 95, "strong": 0, "starve": 220, "clean": 0},
 "yjs-music": {"id": "yjs-music", "object": "音乐", "subject": "music", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生音乐", "charm": 85, "intel": 0, "strong": 0, "starve": 55, "clean": 0},
 "yjs-art": {"id": "yjs-art", "object": "艺术", "subject": "art", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生艺术", "charm": 90, "intel": 90, "strong": 0, "starve": 165, "clean": 110},
 "yjs-manner": {"id": "yjs-manner", "object": "礼仪", "subject": "manner", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生礼仪", "charm": 90, "intel": 0, "strong": 0, "starve": 110, "clean": 55},
 "yjs-pe": {"id": "yjs-pe", "object": "体育", "subject": "pe", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生体育", "charm": 65, "intel": 0, "strong": 85, "starve": 110, "clean": 110},
 "yjs-labouring": {"id": "yjs-labouring", "object": "劳技", "subject": "labouring", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生劳技", "charm": 60, "intel": 0, "strong": 80, "starve": 110, "clean": 55},
 "yjs-wushu": {"id": "yjs-wushu", "object": "武术", "subject": "wushu", "school": "研究生", "class_num_up": 69, "class_num": 95, "class_time": 55, "tolk_name": "研究生武术", "charm": 0, "intel": 0, "strong": 95, "starve": 220, "clean": 220},
}
