"""原版 QQ宠物商店物品目录（由 scripts/extract_qqpet_assets.py 生成，勿手改）。"""
CATALOG = [
 {
  "id": "102010001",
  "name": "圈圈冰激凌",
  "type": "food",
  "price": 5,
  "starve": 90,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010002",
  "name": "跳跳玉米鱼",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010003",
  "name": "月光饼饼",
  "type": "food",
  "price": 10,
  "starve": 180,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010004",
  "name": "果味米米花",
  "type": "food",
  "price": 20,
  "starve": 360,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010005",
  "name": "炸虾盖饭",
  "type": "food",
  "price": 100,
  "starve": 1800,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "recommand"
 },
 {
  "id": "102010006",
  "name": "蹦豆豆卷",
  "type": "food",
  "price": 60,
  "starve": 1080,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010007",
  "name": "青松茶笋",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010008",
  "name": "雨披蛋花",
  "type": "food",
  "price": 90,
  "starve": 1620,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102010009",
  "name": "漂漂孔雀果",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010010",
  "name": "伟大可乐",
  "type": "food",
  "price": 20,
  "starve": 360,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010011",
  "name": "断码香肠",
  "type": "food",
  "price": 80,
  "starve": 1440,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102010012",
  "name": "桃桃布丁",
  "type": "food",
  "price": 10,
  "starve": 180,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010013",
  "name": "怪怪巧克力",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010014",
  "name": "西湖龙井",
  "type": "food",
  "price": 20,
  "starve": 360,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010015",
  "name": "下岛咖啡",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010016",
  "name": "滴答果果",
  "type": "food",
  "price": 20,
  "starve": 360,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010020",
  "name": "冰红茶",
  "type": "food",
  "price": 20,
  "starve": 360,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010021",
  "name": "康师傅红茶",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010022",
  "name": "康师傅绿茶",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010023",
  "name": "金钢竹筒饭",
  "type": "food",
  "price": 100,
  "starve": 1800,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "recommand"
 },
 {
  "id": "102010024",
  "name": "霹雳啪啦糖",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010025",
  "name": "温泉溜溜蛋",
  "type": "food",
  "price": 60,
  "starve": 1080,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010026",
  "name": "五彩沙拉",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010027",
  "name": "蛋黄甩甩饼",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010028",
  "name": "金玉良缘",
  "type": "food",
  "price": 60,
  "starve": 1080,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010029",
  "name": "黑白棋子豆",
  "type": "food",
  "price": 60,
  "starve": 1080,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010030",
  "name": "魔力香草草",
  "type": "food",
  "price": 60,
  "starve": 1080,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010031",
  "name": "人参火果汁",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010032",
  "name": "灵芝仙人掌",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010033",
  "name": "彩虹鱼脆脆",
  "type": "food",
  "price": 80,
  "starve": 1440,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010034",
  "name": "咯咯蛋蛋面",
  "type": "food",
  "price": 80,
  "starve": 1440,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010085",
  "name": "徐福记话梅糖",
  "type": "food",
  "price": 30,
  "starve": 540,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010086",
  "name": "德克士盖饭",
  "type": "food",
  "price": 65,
  "starve": 1170,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010087",
  "name": "德克士袋饭",
  "type": "food",
  "price": 100,
  "starve": 1800,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102010088",
  "name": "南山奶粉",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010089",
  "name": "运动菓珍",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010090",
  "name": "菓珍甜橙味",
  "type": "food",
  "price": 30,
  "starve": 540,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010092",
  "name": "酷睿能量包",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102010095",
  "name": "呦呦柚子茶",
  "type": "food",
  "price": 40,
  "starve": 720,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "103010088",
  "name": "蒙牛酸酸乳",
  "type": "food",
  "price": 50,
  "starve": 900,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020001",
  "name": "震动减肥仪",
  "type": "commodity",
  "price": 20,
  "starve": 0,
  "clean": 720,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102020002",
  "name": "强力电吹风",
  "type": "commodity",
  "price": 30,
  "starve": 0,
  "clean": 1080,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "recommand"
 },
 {
  "id": "102020003",
  "name": "舒爽喷湿器",
  "type": "commodity",
  "price": 10,
  "starve": 0,
  "clean": 360,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020005",
  "name": "舒儿按摩器",
  "type": "commodity",
  "price": 20,
  "starve": 0,
  "clean": 720,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020006",
  "name": "茶爽牙膏",
  "type": "commodity",
  "price": 20,
  "starve": 0,
  "clean": 720,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020007",
  "name": "绒绒毛巾",
  "type": "commodity",
  "price": 25,
  "starve": 0,
  "clean": 900,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102020008",
  "name": "妙味香皂",
  "type": "commodity",
  "price": 30,
  "starve": 0,
  "clean": 1080,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "recommand"
 },
 {
  "id": "102020009",
  "name": "冰爽沐浴液",
  "type": "commodity",
  "price": 50,
  "starve": 0,
  "clean": 1800,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "recommand"
 },
 {
  "id": "102020010",
  "name": "柠檬洗面奶",
  "type": "commodity",
  "price": 40,
  "starve": 0,
  "clean": 1440,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020011",
  "name": "宝宝爽身粉",
  "type": "commodity",
  "price": 30,
  "starve": 0,
  "clean": 1080,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020012",
  "name": "宝宝金水",
  "type": "commodity",
  "price": 15,
  "starve": 0,
  "clean": 540,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020013",
  "name": "含香凝露",
  "type": "commodity",
  "price": 20,
  "starve": 0,
  "clean": 720,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020014",
  "name": "啤酒香波",
  "type": "commodity",
  "price": 65,
  "starve": 0,
  "clean": 2340,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020015",
  "name": "飘飘护发素",
  "type": "commodity",
  "price": 30,
  "starve": 0,
  "clean": 1080,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020016",
  "name": "保湿啧喱",
  "type": "commodity",
  "price": 75,
  "starve": 0,
  "clean": 2700,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020017",
  "name": "自动喷湿器",
  "type": "commodity",
  "price": 25,
  "starve": 0,
  "clean": 900,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102020019",
  "name": "QQ魔镜",
  "type": "commodity",
  "price": 25,
  "starve": 0,
  "clean": 900,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020020",
  "name": "魔幻矿泉泥",
  "type": "commodity",
  "price": 50,
  "starve": 0,
  "clean": 1800,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "recommand"
 },
 {
  "id": "102020021",
  "name": "迷魂防蚊水",
  "type": "commodity",
  "price": 25,
  "starve": 0,
  "clean": 900,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020022",
  "name": "保健生发梳",
  "type": "commodity",
  "price": 75,
  "starve": 0,
  "clean": 2700,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "new"
 },
 {
  "id": "102020023",
  "name": "情人香果",
  "type": "commodity",
  "price": 30,
  "starve": 0,
  "clean": 1080,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "102020024",
  "name": "玫瑰香薰",
  "type": "commodity",
  "price": 40,
  "starve": 0,
  "clean": 1440,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "",
  "rectype": "hot"
 },
 {
  "id": "10001",
  "name": "板蓝根",
  "type": "medicine",
  "price": 50,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗感冒",
  "rectype": ""
 },
 {
  "id": "10002",
  "name": "消食片",
  "type": "medicine",
  "price": 50,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗消化不良",
  "rectype": ""
 },
 {
  "id": "10003",
  "name": "枇杷糖浆",
  "type": "medicine",
  "price": 50,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗咳嗽",
  "rectype": ""
 },
 {
  "id": "10004",
  "name": "清凉油",
  "type": "medicine",
  "price": 50,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗头晕",
  "rectype": ""
 },
 {
  "id": "10005",
  "name": "润肤露",
  "type": "medicine",
  "price": 50,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗皮肤瘙痒",
  "rectype": ""
 },
 {
  "id": "20001",
  "name": "银翘丸",
  "type": "medicine",
  "price": 80,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗重感冒",
  "rectype": ""
 },
 {
  "id": "20002",
  "name": "蓝色消炎水",
  "type": "medicine",
  "price": 80,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗胃炎",
  "rectype": ""
 },
 {
  "id": "20003",
  "name": "甘草剂",
  "type": "medicine",
  "price": 80,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗上呼吸道感染",
  "rectype": ""
 },
 {
  "id": "20004",
  "name": "止痛片",
  "type": "medicine",
  "price": 80,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗偏头痛",
  "rectype": ""
 },
 {
  "id": "20005",
  "name": "薄荷油",
  "type": "medicine",
  "price": 80,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗皮肤干裂",
  "rectype": ""
 },
 {
  "id": "30001",
  "name": "金色消炎水",
  "type": "medicine",
  "price": 120,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗肺炎",
  "rectype": ""
 },
 {
  "id": "30002",
  "name": "龙胆草",
  "type": "medicine",
  "price": 120,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗胃溃疡",
  "rectype": ""
 },
 {
  "id": "30003",
  "name": "定喘丸",
  "type": "medicine",
  "price": 120,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗哮喘",
  "rectype": ""
 },
 {
  "id": "30004",
  "name": "退烧药",
  "type": "medicine",
  "price": 120,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗发高烧",
  "rectype": ""
 },
 {
  "id": "30005",
  "name": "生肌膏",
  "type": "medicine",
  "price": 120,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗皮肤溃疡",
  "rectype": ""
 },
 {
  "id": "40001",
  "name": "噗噗神水",
  "type": "medicine",
  "price": 200,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗肺结核",
  "rectype": ""
 },
 {
  "id": "40002",
  "name": "仙人汤",
  "type": "medicine",
  "price": 200,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗胃癌",
  "rectype": ""
 },
 {
  "id": "40003",
  "name": "通风散",
  "type": "medicine",
  "price": 200,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗支气管炎",
  "rectype": ""
 },
 {
  "id": "40004",
  "name": "何首乌",
  "type": "medicine",
  "price": 200,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗心力衰竭",
  "rectype": ""
 },
 {
  "id": "40005",
  "name": "茶树油",
  "type": "medicine",
  "price": 200,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "用于治疗皮肤溃疡感染",
  "rectype": ""
 },
 {
  "id": "50001",
  "name": "百草丹",
  "type": "medicine",
  "price": 240,
  "starve": 0,
  "clean": 0,
  "charm": 0,
  "intel": 0,
  "strong": 0,
  "desc": "包治百病，一粒见效",
  "rectype": ""
 },
 {
  "id": "60001",
  "name": "还魂丹",
  "type": "medicine",
  "price": 400,
  "starve": 500,
  "clean": 500,
  "charm": 0,
  "intel": 0,
  "strong": 100,
  "desc": "用于复活宠物，也可治百病,吃一颗长生不老！",
  "rectype": "hot"
 }
]
